project_id: maetry
base_url: 'https://api.crowdin.com'
base_path: .
preserve_hierarchy: 1
bundles:
  - 3
  - 5
  - 8
files:
  - source: /Backend/Glossary/**/en/*.json
    ignore:
      - /**/*.swift
    translation: /Backend/Glossary/**/%two_letters_code%/%original_file_name%
    type: json
    update_option: update_as_unapproved
