"project_id": "Maestri"
#"api_token": "personal-access-token"
#"base_path": "."
#"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/IOS/*.xcstrings",
    "translation": "/IOS/%original_file_name%",
    "ignore": [
        "/**/*.swift"
    ],
    "type": "string_catalog",
    "update_option": "update_as_unapproved",
    "labels" : [
      "ios"
    ]
  },
  {
    "source": "/Backend/Glossary/en/*.json",
    "translation": "/Backend/Glossary/%two_letters_code%/%original_file_name%",
    "ignore": [
        "/**/*.swift"
    ],
    "type": "json",
    "update_option": "update_as_unapproved",
    "labels" : [
      "backend"
    ]
  }
]
