project_id: Maestri
base_url: 'https://api.crowdin.com'
base_path: .
preserve_hierarchy: 1
bundles:
  - 1
files:
  - source: /IOS/**/**/*.xcstrings
    ignore:
      - /**/*.swift
    translation: /%original_path%/%original_file_name%
    multilingual: 1
    type: string_catalog
    update_option: update_without_changes
  - source: /Backend/Glossary/%original_file_name%/en/*.json
    ignore:
      - /**/*.swift
    translation: /Backend/Glossary/%original_file_name%/%two_letters_code%/%original_file_name%
    type: json
    update_option: update_as_unapproved
