project_identifier: Maestri
api_key_env: CROWDIN_API_KEY
base_path: .
files:
  - source: /**/*
    ignore:
      - /**/*.swift
      - /*.md
      - /*.gitignore
    translation: /%original_path%/%original_file_name%
    multilingual: 1
bundles:
  - 1
