project_id: Maestri
base_url: 'https://api.crowdin.com'
base_path: .
preserve_hierarchy: 1
files:
  - source: /IOS/*.xcstrings
    ignore:
      - /**/*.swift
    translation: /IOS/%original_file_name%
#    multilingual: 1
    type: string_catalog
    update_option: update_as_unapproved
  - source: /Backend/Glossary/en/*.json
    ignore:
      - /**/*.swift
    translation: /Backend/Glossary/%two_letters_code%/%original_file_name%
    type: json
    update_option: update_as_unapproved
bundles:
  - 1
